export const PACKAGE_NAME = "@itaa/ui-kit";
export const PACKAGE_STATUS = "design-system";

export {
  FOCUS_RING_CLASS,
  LIVE_REGION_CLASS,
  liveRegionHtml,
  shouldAnnounce,
  VISUALLY_HIDDEN_CLASS,
  visuallyHiddenHtml,
  withFocusRing,
  type LivePoliteness,
  type LiveRegionProps,
} from "./accessibility/index.js";
export {
  CONTRAST_LARGE_TEXT_MIN,
  CONTRAST_NON_TEXT_MIN,
  CONTRAST_TEXT_MIN,
  contrastRatio,
  relativeLuminance,
} from "./contrast.js";
export {
  BUTTON_STATES,
  BUTTON_VARIANTS,
  buttonHtml,
  SIMULATION_BANNER_DENSITIES,
  SIMULATION_BANNER_LABEL,
  SIMULATION_BANNER_PLACEMENTS,
  simulationBannerHtml,
  STATUS_VARIANTS,
  statusIndicatorHtml,
  surfaceHtml,
  TEXT_ROLES,
  textHtml,
  type ButtonProps,
  type ButtonState,
  type ButtonVariant,
  type SimulationBannerDensity,
  type SimulationBannerPlacement,
  type SimulationBannerProps,
  type StatusIndicatorProps,
  type StatusVariant,
  type SurfaceProps,
  type TextProps,
  type TextTag,
} from "./primitives/index.js";
export { renderStylesheet } from "./stylesheet.js";
export {
  breakpointsPx,
  borderWidthPx,
  COLOR_USAGE,
  colorRoles,
  CSS_VAR,
  elevation,
  focusTreatment,
  fontFamilies,
  implementedThemes,
  layers,
  layoutPx,
  lightColorRoles,
  lightTints,
  LOCKED_LIGHT_COLORS,
  mixSrgb,
  motion,
  parseHex,
  radiusPx,
  SEMANTIC_TOKEN_NAMES,
  semanticToken,
  spacingPx,
  spacingScalePx,
  themeSlots,
  TINT_MIX,
  touchTargetPx,
  typeRoles,
  type ColorRoles,
  type HexColor,
  type SemanticTokenName,
  type ThemeSlot,
  type TypeRole,
} from "./tokens/index.js";
